### ISSUE TITLE
Feature request: Filter stats by function descriptor

### ISSUE THREAD

**Issue by sm-Fifteen** [sumerc/yappi#41]
As part of an application profiler plugin project for the ASGI protocol, where users can just pass a list of functions to profile, I was using a simple `yappi.get_func_stats({"name": somefunction.__qualname__, "tag": ctx_tag})` filter, thinking it would be enough to unambigously select those functions. I later found out that `__qualname__` is only unambiguous within the scope of a module, so I should in all likelyhood specify `somefunction.__module__` as part of the filter as well, but that got me to look at the code yappi uses to identify the functions being called:

https://github.com/sumerc/yappi/blob/6c97f55ae69a0979bdea8e557510a5d349da340c/yappi/_yappi.c#L546-L567

It uses `ml_name` as the function name, [which apparently corresponds to `__name__`, not `__qualname__`](https://github.com/python/cpython/blob/4dedd0f0ddc5a983a57bf0105eb34f948a91d2c4/Objects/methodobject.c#L152-L156) like I initially figured yappi would use, and has a few edge-cases for both function and module name that could make it difficult/unreliable to build the correct filter automatically.

Shouldn't yappi have some kind of `filter_from_function_descriptor` function to generate a detailled filter from a function descriptor automatically, instead of leaving users guessing as to whether they're accidentally profiling other functions with the same name as the one they want?

**Comment by sm-Fifteen** [comment]
Related to #22.

**Comment by sumerc** [comment]
Good point!

Please correct me if I am wrong:

An example: you have a nested function like this:
```python
class A:
    class B:
        class C:
            def f(self):
                pass
```
And you cannot filter on function `f` because the `name` generated in Yappi is not deterministic enough. In other words, `name` might change depending on where it is defined. Right?

I think there are two issues here:
- We should use `__qualname__` instead of `__name__` if Python version is 3.3 and up. (Note: I am surprised `cProfile` has not implemented this, too.)
- We should be able to filter on function itself somehow in a deterministic way regardless of its string representation. One idea might be to use `PyCodeObject`? e.g: `.get_func_stats(filter={'code': func.__code__})`.

**Comment by sm-Fifteen** [comment]
Actually, my initial concern was a lot simpler than that:

```py
>>> from time import sleep as sleep1
>>> from asyncio import sleep as sleep2
>>> sleep1.__qualname__
'sleep'
>>> sleep2.__qualname__
'sleep'
```

If we blindly filter by `{'name':sleep1.__qualname__}` and don't remember to filter by module as well, the result object will contain both

----

But since we're here, I just did a quick and dirty check and the following code:

```py
@router.get('/testfoo')
async def testfoo():
    class A:
        class B:
            class C:
                async def f(self):
                    await asyncio.sleep(5)

    await A.B.C().f()
    return {'name': A.B.C().f.__name__, "qualname": A.B.C().f.__qualname__}
```

Gets profiled as follows:

```
index: 3265
full_name: .\app\testfoo.py:140 testfoo
ncall: 1/1
ttot: 5.008828
tsub: 0.000012
children:

     index: 3270
     child_full_name: .\app\testfoo.py:145 C.f
     ncall: 1/1
     ttot: 5.008768
     tsub: 0.000008
```

```json
`{"name":"f","qualname":"testfoo.<locals>.A.B.C.f"}`
```

It looks like neither of them matches against a name filter, only "C.f" works.

That's admittedly a fairly convoluted case, but it's just another case where building the filter by hand can get obscure, error-prone and lead to an incorrect reading of the result data.

This example (wrappers, a much more common python pattern):

```py
def bar():
    import asyncio
    async def baz():
        await asyncio.sleep(5)

    return baz

@router.get('/testfoo')
async def testfoo():
    runme = bar()
    await runme()
    
    return {'name': runme.__name__, "qualname": runme.__qualname__}
```

```
index: 2840
full_name: .\app\testfoo.py:147 testfoo
ncall: 1/1
ttot: 5.000080
tsub: 0.000007
children:

     index: 2842
     child_full_name: .\app\testfoo.py:142 baz
     ncall: 1/1
     ttot: 5.000069
     tsub: 0.000010

     index: 2841
     child_full_name: .\app\testfoo.py:140 bar
     ncall: 1/1
     ttot: 0.000004
     tsub: 0.000004
```

```json
{"name":"baz","qualname":"bar.<locals>.baz"}
```

...can also easily make for some ambiguous and tricky to manipulate results.
